### ISSUE TITLE
Delete checked out PR branches

### ISSUE THREAD

**Issue by msfjarvis** [seachicken/gh-poi#25]
**Description**
When a PR branch is currently checked out, `gh-poi` will not delete the branch. A way to fix this would be to checkout the default branch and _then_ delete the branch. 

**Additional context**

[hub-sync](https://hub.github.com/hub-sync.1.html) implemented this same functionality and the way I described above is how this tool dealt with the problem.

**Comment by seachicken** [comment]
Thanks for the suggestion 😄
Being able to delete merged branches even if they are checked out seems like a good idea as it will make development smoother.
I'll refer to hub-sync and see if there are any issues.

**Comment by seachicken** [comment]
Here's what I'm thinking:
- If the local branch contains uncommitted changes, don't delete the current branch. (simple implementation first)
- If a checked-out branch is already merged and can be deleted, delete it after the default branch is checked out.
- If the `--check` option is enabled, the checkout is not actually executed.

**Comment by msfjarvis** [comment]
Sounds good 👍🏼
