### ISSUE TITLE
Fails to delete checked out PR branch when PR HEAD branch is named same as default branch

### ISSUE THREAD

**Issue by msfjarvis** [seachicken/gh-poi#37]
**Describe the bug**

Given a PR like [this](https://msfjarvis.dev/aps/pr/1781) which is raised against the `develop` branch, from the `develop` branch of a fork, `gh pr checkout 1781` creates the `c-steindl/develop` branch locally. Running `gh poi` after merging the PR does not delete this branch.

**Your Environment**
 - OS: Linux Mint 20.3
 - gh --version: gh version 2.5.1 (1980-01-01)

**Comment by seachicken** [comment]
Thanks for the report!
This is a usage that has not been taken into account. I think it would be ideal to be able to remove it, so I will proceed with the modification.

**Comment by seachicken** [comment]
@msfjarvis I think I could fix it, please update.
`gh extension upgrade poi`
https://github.com/seachicken/gh-poi/releases/tag/v0.4.0

It would be great if you could let me know if there are any more problems 😃

**Comment by msfjarvis** [comment]
That works, thanks a lot for promptly fixing this!
