### ISSUE TITLE
How to use with  local github on non-standard http port? 

### ISSUE THREAD

**Issue by uyriq** [seachicken/gh-poi#99]
https://github.com/seachicken/gh-poi/blob/a2a845b80dfef7251b62fcb50589fd84e99049ed/conn/command.go#L13

```
gh poi -debug
2023/03/26 17:15:46 [1.060508ms] run git [remote -v] -> origin	git@mylocalgitbox.local:uyriq/my-local.git (fetch)
origin	git@mylocalgitbox:uyriq/my-local.git (push)

2023/03/26 17:15:46 [5.152972ms] run ssh [-T -G mylocalgitbox.local] -> *****
2023/03/26 17:15:46 [13.030318ms] run gh [repo view mylocalgitbox.local/user/my-local --json owner,name,parent,defaultBranchRef --jq .] -> 
✕ Fetching pull requests...
failed to run external command: gh, args: [repo view mylocalgitbox.local/user/my-local  --json owner,name,parent,defaultBranchRef --jq .]
exit status 1

```

this is due the fact that mylocalgitbox.local not run on 80 port but on 8080

**Comment by seachicken** [comment]
Hello, I have a few questions.
- What is mylocalgitbox.local?
- Can you run the `gh repo view` command? (this tool works with some features of the parent [gh cli](https://github.com/cli/cli))

**Comment by uyriq** [comment]
`gh repo view mylocalgitbox.local:8080/uyriq/my-local-project
`
`Post "https://mylocalgitbox.local:8080/api/graphql": http: server gave HTTP response to HTTPS client` 
due depend on gh api, seems this won't work?

**Comment by seachicken** [comment]
No response, so I will close it. Please open it if you have any additional information.
